/**
 * src/types/database.ts
 *
 * Supabase database type definitions for Spotlight.
 *
 * Follows the shape generated by `supabase gen types typescript`.
 * Hand-authored to match the migration schema in supabase/migrations/.
 *
 * Usage with the Supabase client:
 *   import type { Database } from '@/types/database';
 *   const client = createClient<Database>(url, key);
 *   const { data } = await client.from('acts').select('*');
 *   // data is typed as Database['public']['Tables']['acts']['Row'][]
 *
 * Helper aliases are exported at the bottom for ergonomic access.
 * Do not duplicate domain types already in src/types/index.ts —
 * database types represent the raw DB row shape, not the UI domain shape.
 */

// ─── Enum Definitions ─────────────────────────────────────────────────────────

export type EventStatus = 'DRAFT' | 'READY' | 'LIVE' | 'PAUSED' | 'ENDED';
export type ActCategory = 'SOLO' | 'GROUP';
export type ActStatus = 'PENDING' | 'APPROVED' | 'REJECTED';
export type PaymentStatus = 'PENDING' | 'PAID' | 'FAILED' | 'CANCELLED';
export type ActorType = 'ADMIN' | 'JUDGE' | 'SYSTEM';

export type EventLogAction =
  | 'ACT_STARTED'
  | 'VOTING_OPENED'
  | 'VOTING_CLOSED'
  | 'ACT_ENDED'
  | 'NEXT_ACT'
  | 'EVENT_PAUSED'
  | 'EVENT_RESUMED'
  | 'REGISTRATION_APPROVED'
  | 'REGISTRATION_REJECTED'
  | 'JUDGE_SCORE_SUBMITTED';

// ─── Table Row Types ──────────────────────────────────────────────────────────

export interface EventRow {
  id: string;
  name: string;
  description: string | null;
  event_date: string | null;
  venue: string | null;
  capacity: number;
  ticket_price: number;
  status: EventStatus;
  current_act_id: string | null;
  voting_open: boolean;
  created_at: string;
  updated_at: string;
}

export interface ActRow {
  id: string;
  act_code: string;           // unique e.g. SPT-2026-0001
  category: ActCategory;
  title: string;
  performer_name: string;
  department: string | null;
  year: string | null;
  phone: string | null;
  email: string | null;
  photo_url: string | null;
  performance_type: string | null;
  bio: string | null;
  self_rating: number | null;  // 1–10
  status: ActStatus;
  running_order: number | null;
  created_at: string;
  updated_at: string;
}

export interface ActMemberRow {
  id: string;
  act_id: string;             // FK → acts.id
  name: string;
  department: string | null;
  year: string | null;
  created_at: string;
}

export interface JudgeRow {
  id: string;
  name: string;
  email: string | null;
  judge_code: string;         // unique e.g. JUDGE-01
  is_anchor: boolean;         // anchor judge used for tie-breaking
  is_active: boolean;
  auth_user_id?: string | null;
  created_at: string;
}

export interface JudgeScoreRow {
  id: string;
  act_id: string;             // FK → acts.id
  judge_id: string;           // FK → judges.id
  creativity: number;         // 0–3
  execution: number;          // 0–3
  stage_presence: number;     // 0–2
  audience_engagement: number; // 0–2
  // NOTE: total is NOT stored — calculated by scoreService:
  //   total = creativity + execution + stage_presence + audience_engagement
  notes: string | null;
  submitted: boolean;
  submitted_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface TicketRow {
  id: string;
  ticket_code: string;        // unique e.g. SPT-TKT-2026-0001
  buyer_name: string;
  buyer_email: string;
  buyer_phone: string | null;
  quantity: number;
  payment_status: PaymentStatus;
  payment_reference: string | null;  // Razorpay order_id (Phase 8C+)
  issued_at: string | null;
  created_at: string;
}

export interface AudienceVoteRow {
  id: string;
  ticket_id: string;          // FK → tickets.id
  act_id: string;             // FK → acts.id
  rating: number;             // 1–10
  created_at: string;
  // UNIQUE(ticket_id, act_id) enforced at DB level
}

export interface AdminUserRow {
  id: string;                 // matches auth.users.id (Supabase Auth UID)
  email: string;
  name: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface EventLogRow {
  id: string;
  event_id: string;           // FK → events.id
  actor_type: ActorType;
  actor_id: string | null;    // judge_id or admin_id or null for SYSTEM
  action: EventLogAction;
  metadata: Record<string, unknown> | null;  // JSONB
  created_at: string;
}

// ─── Insert Types ─────────────────────────────────────────────────────────────

export interface EventInsert {
  id?: string;
  name: string;
  description?: string | null;
  event_date?: string | null;
  venue?: string | null;
  capacity?: number;
  ticket_price?: number;
  status?: EventStatus;
  current_act_id?: string | null;
  voting_open?: boolean;
  created_at?: string;
  updated_at?: string;
}

export interface ActInsert {
  id?: string;
  act_code: string;
  category: ActCategory;
  title: string;
  performer_name: string;
  department?: string | null;
  year?: string | null;
  phone?: string | null;
  email?: string | null;
  photo_url?: string | null;
  performance_type?: string | null;
  bio?: string | null;
  self_rating?: number | null;
  status?: ActStatus;
  running_order?: number | null;
  created_at?: string;
  updated_at?: string;
}

export interface ActMemberInsert {
  id?: string;
  act_id: string;
  name: string;
  department?: string | null;
  year?: string | null;
  created_at?: string;
}

export interface JudgeInsert {
  id?: string;
  name: string;
  email?: string | null;
  judge_code: string;
  is_anchor?: boolean;
  is_active?: boolean;
  created_at?: string;
}

export interface JudgeScoreInsert {
  id?: string;
  act_id: string;
  judge_id: string;
  creativity: number;
  execution: number;
  stage_presence: number;
  audience_engagement: number;
  notes?: string | null;
  submitted?: boolean;
  submitted_at?: string | null;
  created_at?: string;
  updated_at?: string;
}

export interface TicketInsert {
  id?: string;
  ticket_code: string;
  buyer_name: string;
  buyer_email: string;
  buyer_phone?: string | null;
  quantity?: number;
  payment_status?: PaymentStatus;
  payment_reference?: string | null;
  issued_at?: string | null;
  created_at?: string;
}

export interface AudienceVoteInsert {
  id?: string;
  ticket_id: string;
  act_id: string;
  rating: number;
  created_at?: string;
}

export interface AdminUserInsert {
  id: string;
  email: string;
  name: string;
  is_active?: boolean;
  created_at?: string;
  updated_at?: string;
}

export interface EventLogInsert {
  id?: string;
  event_id: string;
  actor_type: ActorType;
  actor_id?: string | null;
  action: EventLogAction;
  metadata?: Record<string, unknown> | null;
  created_at?: string;
}

// ─── Update Types ─────────────────────────────────────────────────────────────

export type ActUpdate = Partial<ActInsert>;
export type JudgeScoreUpdate = Partial<JudgeScoreInsert>;
export type EventUpdate = Partial<EventInsert>;
export type AdminUserUpdate = Partial<Omit<AdminUserInsert, 'id'>>;


// ─── Supabase Database Shape ──────────────────────────────────────────────────
// Follows the shape expected by createClient<Database>()

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      events: {
        Row: EventRow;
        Insert: EventInsert;
        Update: EventUpdate;
        Relationships: [];
      };
      acts: {
        Row: ActRow;
        Insert: ActInsert;
        Update: ActUpdate;
        Relationships: [];
      };
      act_members: {
        Row: ActMemberRow;
        Insert: ActMemberInsert;
        Update: Partial<ActMemberInsert>;
        Relationships: [
          {
            foreignKeyName: "act_members_act_id_fkey";
            columns: ["act_id"];
            isOneToOne: false;
            referencedRelation: "acts";
            referencedColumns: ["id"];
          }
        ];
      };
      judges: {
        Row: JudgeRow;
        Insert: JudgeInsert;
        Update: Partial<JudgeInsert>;
        Relationships: [];
      };
      judge_scores: {
        Row: JudgeScoreRow;
        Insert: JudgeScoreInsert;
        Update: JudgeScoreUpdate;
        Relationships: [
          {
            foreignKeyName: "judge_scores_act_id_fkey";
            columns: ["act_id"];
            isOneToOne: false;
            referencedRelation: "acts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "judge_scores_judge_id_fkey";
            columns: ["judge_id"];
            isOneToOne: false;
            referencedRelation: "judges";
            referencedColumns: ["id"];
          }
        ];
      };
      tickets: {
        Row: TicketRow;
        Insert: TicketInsert;
        Update: Partial<TicketInsert>;
        Relationships: [];
      };
      audience_votes: {
        Row: AudienceVoteRow;
        Insert: AudienceVoteInsert;
        Update: never;  // votes are immutable once cast
        Relationships: [
          {
            foreignKeyName: "audience_votes_act_id_fkey";
            columns: ["act_id"];
            isOneToOne: false;
            referencedRelation: "acts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "audience_votes_ticket_id_fkey";
            columns: ["ticket_id"];
            isOneToOne: false;
            referencedRelation: "tickets";
            referencedColumns: ["id"];
          }
        ];
      };
      admin_users: {
        Row: AdminUserRow;
        Insert: AdminUserInsert;
        Update: AdminUserUpdate;
        Relationships: [];
      };
      event_logs: {
        Row: EventLogRow;
        Insert: EventLogInsert;
        Update: never;  // logs are append-only
        Relationships: [
          {
            foreignKeyName: "event_logs_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: false;
            referencedRelation: "events";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      submit_audience_vote: {
        Args: {
          ticket_code_input: string;
          rating_input: number;
        };
        Returns: Json;
      };
      get_current_voting_state: {
        Args: {
          ticket_code_input?: string | null;
        };
        Returns: Json;
      };
      get_judge_by_code: {
        Args: {
          judge_code_input: string;
        };
        Returns: Json;
      };
      get_judge_score_for_act: {
        Args: {
          judge_code_input: string;
          act_id_input: string;
        };
        Returns: Json;
      };
      submit_judge_score: {
        Args: {
          judge_code_input: string;
          act_id_input: string;
          creativity_input: number;
          execution_input: number;
          stage_presence_input: number;
          audience_engagement_input: number;
          notes_input?: string | null;
        };
        Returns: Json;
      };
      admin_approve_registration: {
        Args: {
          act_id_input: string;
        };
        Returns: Json;
      };
      admin_reject_registration: {
        Args: {
          act_id_input: string;
        };
        Returns: Json;
      };
      admin_set_current_act: {
        Args: {
          act_id_input: string;
        };
        Returns: Json;
      };
      admin_update_event_state: {
        Args: {
          p_status?: string | null;
          p_voting_open?: boolean | null;
          p_current_act_id?: string | null;
        };
        Returns: Json;
      };
      admin_get_overview_stats: {
        Args: Record<string, never>;
        Returns: Json;
      };
      purchase_tickets_atomic: {
        Args: {
          p_buyer_name: string;
          p_buyer_email: string;
          p_buyer_phone: string;
          p_quantity: number;
          p_payment_method?: string;
        };
        Returns: Json;
      };
    };
    Enums: {
      event_status: EventStatus;
      act_category: ActCategory;
      act_status: ActStatus;
      payment_status: PaymentStatus;
      actor_type: ActorType;
      event_log_action: EventLogAction;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

// ─── Convenience Row Aliases ──────────────────────────────────────────────────
// Use these in services for cleaner type annotations.

export type DbEvent = Database['public']['Tables']['events']['Row'];
export type DbAct = Database['public']['Tables']['acts']['Row'];
export type DbActMember = Database['public']['Tables']['act_members']['Row'];
export type DbJudge = Database['public']['Tables']['judges']['Row'];
export type DbJudgeScore = Database['public']['Tables']['judge_scores']['Row'];
export type DbTicket = Database['public']['Tables']['tickets']['Row'];
export type DbAudienceVote = Database['public']['Tables']['audience_votes']['Row'];
export type DbAdminUser = Database['public']['Tables']['admin_users']['Row'];
export type DbEventLog = Database['public']['Tables']['event_logs']['Row'];
