/**
 * src/types/database.ts
 *
 * Supabase database type definitions for Spotlight.
 *
 * Follows the shape generated by `supabase gen types typescript`.
 * Hand-authored to match the migration schema in supabase/migrations/.
 *
 * Usage with the Supabase client:
 *   import type { Database } from '@/types/database';
 *   const client = createClient<Database>(url, key);
 *   const { data } = await client.from('acts').select('*');
 *   // data is typed as Database['public']['Tables']['acts']['Row'][]
 *
 * Helper aliases are exported at the bottom for ergonomic access.
 * Do not duplicate domain types already in src/types/index.ts —
 * database types represent the raw DB row shape, not the UI domain shape.
 */

// ─── Enum Definitions ─────────────────────────────────────────────────────────

export type EventStatus = 'DRAFT' | 'READY' | 'LIVE' | 'PAUSED' | 'ENDED';
export type ActCategory = 'SOLO' | 'GROUP';
export type ActStatus = 'PENDING' | 'APPROVED' | 'REJECTED';
export type PaymentStatus = 'PENDING' | 'PAID' | 'FAILED' | 'CANCELLED';
export type ActorType = 'ADMIN' | 'JUDGE' | 'SYSTEM';

export type EventLogAction =
  | 'ACT_STARTED'
  | 'VOTING_OPENED'
  | 'VOTING_CLOSED'
  | 'ACT_ENDED'
  | 'NEXT_ACT'
  | 'EVENT_PAUSED'
  | 'EVENT_RESUMED'
  | 'REGISTRATION_APPROVED'
  | 'REGISTRATION_REJECTED'
  | 'JUDGE_SCORE_SUBMITTED';

// ─── Table Row Types ──────────────────────────────────────────────────────────

export interface EventRow {
  id: string;
  name: string;
  description: string | null;
  event_date: string | null;
  venue: string | null;
  capacity: number;
  ticket_price: number;
  status: EventStatus;
  current_act_id: string | null;
  voting_open: boolean;
  created_at: string;
  updated_at: string;
}

export interface ActRow {
  id: string;
  act_code: string;           // unique e.g. SPT-2026-0001
  category: ActCategory;
  title: string;
  performer_name: string;
  department: string | null;
  year: string | null;
  phone: string | null;
  email: string | null;
  photo_url: string | null;
  performance_type: string | null;
  bio: string | null;
  self_rating: number | null;  // 1–10
  status: ActStatus;
  running_order: number | null;
  created_at: string;
  updated_at: string;
}

export interface ActMemberRow {
  id: string;
  act_id: string;             // FK → acts.id
  name: string;
  department: string | null;
  year: string | null;
  created_at: string;
}

export interface JudgeRow {
  id: string;
  name: string;
  email: string | null;
  judge_code: string;         // unique e.g. JUDGE-01
  is_anchor: boolean;         // anchor judge used for tie-breaking
  is_active: boolean;
  created_at: string;
}

export interface JudgeScoreRow {
  id: string;
  act_id: string;             // FK → acts.id
  judge_id: string;           // FK → judges.id
  creativity: number;         // 0–3
  execution: number;          // 0–3
  stage_presence: number;     // 0–2
  audience_engagement: number; // 0–2
  // NOTE: total is NOT stored — calculated by scoreService:
  //   total = creativity + execution + stage_presence + audience_engagement
  notes: string | null;
  submitted: boolean;
  submitted_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface TicketRow {
  id: string;
  ticket_code: string;        // unique e.g. SPT-TKT-2026-0001
  buyer_name: string;
  buyer_email: string;
  buyer_phone: string | null;
  quantity: number;
  payment_status: PaymentStatus;
  payment_reference: string | null;  // Razorpay order_id (Phase 8C+)
  issued_at: string | null;
  created_at: string;
}

export interface AudienceVoteRow {
  id: string;
  ticket_id: string;          // FK → tickets.id
  act_id: string;             // FK → acts.id
  rating: number;             // 1–10
  created_at: string;
  // UNIQUE(ticket_id, act_id) enforced at DB level
}

export interface AdminUserRow {
  id: string;                 // matches auth.users.id (Supabase Auth UID)
  email: string;
  name: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface EventLogRow {
  id: string;
  event_id: string;           // FK → events.id
  actor_type: ActorType;
  actor_id: string | null;    // judge_id or admin_id or null for SYSTEM
  action: EventLogAction;
  metadata: Record<string, unknown> | null;  // JSONB
  created_at: string;
}

// ─── Insert Types (omit auto-generated fields) ────────────────────────────────

export type EventInsert = Omit<EventRow, 'id' | 'created_at' | 'updated_at'>;
export type ActInsert = Omit<ActRow, 'id' | 'created_at' | 'updated_at'>;
export type ActMemberInsert = Omit<ActMemberRow, 'id' | 'created_at'>;
export type JudgeInsert = Omit<JudgeRow, 'id' | 'created_at'>;
export type JudgeScoreInsert = Omit<JudgeScoreRow, 'id' | 'created_at' | 'updated_at'>;
export type TicketInsert = Omit<TicketRow, 'id' | 'created_at'>;
export type AudienceVoteInsert = Omit<AudienceVoteRow, 'id' | 'created_at'>;
export type AdminUserInsert = Omit<AdminUserRow, 'created_at' | 'updated_at'>;
export type EventLogInsert = Omit<EventLogRow, 'id' | 'created_at'>;

// ─── Update Types ─────────────────────────────────────────────────────────────

export type ActUpdate = Partial<ActInsert>;
export type JudgeScoreUpdate = Partial<JudgeScoreInsert>;
export type EventUpdate = Partial<EventInsert>;
export type AdminUserUpdate = Partial<Omit<AdminUserInsert, 'id'>>;

// ─── Supabase Database Shape ──────────────────────────────────────────────────
// Follows the shape expected by createClient<Database>()

export interface Database {
  public: {
    Tables: {
      events: {
        Row: EventRow;
        Insert: EventInsert;
        Update: EventUpdate;
      };
      acts: {
        Row: ActRow;
        Insert: ActInsert;
        Update: ActUpdate;
      };
      act_members: {
        Row: ActMemberRow;
        Insert: ActMemberInsert;
        Update: Partial<ActMemberInsert>;
      };
      judges: {
        Row: JudgeRow;
        Insert: JudgeInsert;
        Update: Partial<JudgeInsert>;
      };
      judge_scores: {
        Row: JudgeScoreRow;
        Insert: JudgeScoreInsert;
        Update: JudgeScoreUpdate;
      };
      tickets: {
        Row: TicketRow;
        Insert: TicketInsert;
        Update: Partial<TicketInsert>;
      };
      audience_votes: {
        Row: AudienceVoteRow;
        Insert: AudienceVoteInsert;
        Update: never;  // votes are immutable once cast
      };
      admin_users: {
        Row: AdminUserRow;
        Insert: AdminUserInsert;
        Update: AdminUserUpdate;
      };
      event_logs: {
        Row: EventLogRow;
        Insert: EventLogInsert;
        Update: never;  // logs are append-only
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      event_status: EventStatus;
      act_category: ActCategory;
      act_status: ActStatus;
      payment_status: PaymentStatus;
      actor_type: ActorType;
      event_log_action: EventLogAction;
    };
  };
}

// ─── Convenience Row Aliases ──────────────────────────────────────────────────
// Use these in services for cleaner type annotations.

export type DbEvent = Database['public']['Tables']['events']['Row'];
export type DbAct = Database['public']['Tables']['acts']['Row'];
export type DbActMember = Database['public']['Tables']['act_members']['Row'];
export type DbJudge = Database['public']['Tables']['judges']['Row'];
export type DbJudgeScore = Database['public']['Tables']['judge_scores']['Row'];
export type DbTicket = Database['public']['Tables']['tickets']['Row'];
export type DbAudienceVote = Database['public']['Tables']['audience_votes']['Row'];
export type DbAdminUser = Database['public']['Tables']['admin_users']['Row'];
export type DbEventLog = Database['public']['Tables']['event_logs']['Row'];
